### ISSUE TITLE
why not  the embedding_table shared by different Bert instances ?

### ISSUE THREAD

**Issue by everwind** [zhihu/cuBERT#27]
template<typename T, typename V>
    Embedding<T, V>::Embedding(size_t vocab_size, size_t embedding_size, V *embedding_table) {
        this->vocab_size = vocab_size;
        this->embedding_size = embedding_size;
        this->embedding_table = static_cast<V *>(cuBERT::malloc(vocab_size * embedding_size * sizeof(V)));
        cuBERT::memcpy(this->embedding_table, embedding_table, vocab_size * embedding_size * sizeof(V), 1);
    }

The BertM create several Bert instances,  and  every Bert instances will malloc a new Embedding table,  why not different Bert instances share the common Embedding table? This will save a lot of memory .

**Comment by levyfan** [comment]
Because for GPU, different instance is on different card, and the memory can't be shared. For CPU, it is OK to share the embedding table.

**Comment by everwind** [comment]
> Because for GPU, different instance is on different card, and the memory can't be shared. For CPU, it is OK to share the embedding table.

是的，在cpu 模式下，真的有必要让bert 的参数共享， 特别是在多线程情况，每新建一个bert 实例就 多占用一个bert 模型大小的内存空间，还是非常不方便的。后续这一块有改进的计划吗？ 改成在GPU 的情况下就是内存复制一份模型参数到对应的卡，在cpu 的模式下，不同的bert 实例共享一份模型参数，这样感觉更合理一下，也更省内存。

**Comment by levyfan** [comment]
你是在什么情况下需要更优化的内存？目前我们这边的需求不强，因为 BERT 本身词表不大，只有 20k，因此内存占用也就 20k * 768 * 4 约为 61M。这样既是按照 README 里面的 CUBERT_NUM_CPU_MODELS=5 也就只使用 300M 内存。

**Comment by levyfan** [comment]
即使是多线程，你也可以只使用一个 BERT 实例，因为 BERT 内部本身的操作 op 都是并发的（比如矩阵乘法，softmax 等等），会占用所有`可用`的 CPU 资源。

**Comment by everwind** [comment]
> 你是在什么情况下需要更优化的内存？目前我们这边的需求不强，因为 BERT 本身词表不大，只有 20k，因此内存占用也就 20k * 768 * 4 约为 61M。这样即使按照 README 里面的 CUBERT_NUM_CPU_MODELS=5 也就只使用 300M 内存。

不是只有 词表的参数要共享，而是整个bert 的模型参数都共享， 这一块 5*400M 有2G 的内存开销。 另外，cpu的场景下，想做成无锁的模式，比如每个线程有一个 Bert 实例，因为参数都共享了。所以 一个Bert 实例的内存就很小，每一个线程独享一个Bert 实例，问题不大。

**Comment by levyfan** [comment]
> 一个Bert 实例的内存就很小

这个是不对的，除去模型参数之外，每个 BERT 实例还有内部 op 的大量输入输出 Buffer，这部分的内存占用是由 max_batch_size 决定。

> 想做成无锁的模式
> 每一个线程独享一个Bert实例

为什么要这样？这种情况下每一次 BERT.compute 只能够有效使用一个线程，放弃了 openmp 和 MKL 提供的并行方案。这种方案每次调用的 latency 是很大的。另外，即使每个线程独享BERT实例，那么外部请求到来时，仍然无法免除任务队列和排队（类似于线程池模式）。还有就是目前的实现里，锁的作用是保护内部 op 的输入输出 Buffer，相比于计算过程，锁的开销微乎其微。

> 这一块 5*400M 有 2G 的内存开销

在目前大容量内存服务器那么普及的情况下（普遍 128G+），这一些内存占用并没有那么重要吧。

其实最主要还是在于你这儿的需求是怎么样的。

**Comment by levyfan** [comment]
Anyway, 共享模型参数不难修改，目前 Graph 会驻留整个生命周期，所以不用考虑它提前析构导致的野指针问题。更合适的是把目前的裸指针 T* 更改为智能指针，比如将 Graph.var 修改为 `std::unordered_map<std::string, std::shared_ptr<T> >`。

**Comment by everwind** [comment]
类似百度 paddle 这种使用方式

auto main_predictor = paddle::CreatePaddlePredictor(config);

const int num_threads = 10;  // 假设有 10 个服务线程
std::vector<std::thread> threads;
std::vector<decl_type(main_predictor)> predictors;

// 最好初始化时把所有predictor都创建好
predictors.emplace_back(std::move(main_predictor));
for (int i = 1; i < num_threads; i++) {
    predictors.emplace_back(main_predictor->Clone());
}
// 创建线程并执行
for (int i = 0; i < num_threads; i++) {
    threads.emplace_back([i, &]{
        auto& predictor = predictors[i];
        // 执行
        CHECK(predictor->Run(...));
    });
}

// 结尾
for (auto& t : threads) {
    if (t.joinable()) t.join();
}

// 结束
