### ISSUE TITLE
EMBEDDING_OUTPUT

### ISSUE THREAD

**Issue by Jackie127** [zhihu/cuBERT#28]
output_type=cuBERT.OutputType.LOGITS
compute_type=cuBERT.ComputeType.FLOAT
output = np.zeros([batch_size], dtype=np.float32, order='C')
如果要输出EMBEDING_OUTPUT,上述参数如何修改。

**Comment by levyfan** [comment]
output_type=cuBERT.OutputType.EMBEDDING_OUTPUT
compute_type=cuBERT.ComputeType.FLOAT
output = np.zeros([batch_size, seq_length, hidden_size], dtype=np.float32, order='C')
