### ISSUE TITLE
pooled_output

### ISSUE THREAD

**Issue by Jackie127** [zhihu/cuBERT#29]
请问cubert的model.get_pooled_output()是否与原始bert的model.get_pooled_output一致,
model.tokenize_compute(text_a, text_b, output, output_type=output_type),text_b设置为None,
,output_type设置为cuBERT_POOLED_OUTPUT，是表示对text_a进行embedding吗，对text_a进行表征时,text_a前后有加入CLS和SEP吗，bert_frozen_seq32.pb是从bert提供的BERT-Base, Chinese转过来的吗，能否提供.ckpt转化为.pb的代码

**Comment by levyfan** [comment]
> 是否与原始bert的model.get_pooled_output一致

是

> 是表示对text_a进行embedding吗

是

> text_a前后有加入CLS和SEP吗

是，和 https://github.com/google-research/bert/blob/0fce551b55caabcfba52c61e18f34b541aef186a/run_classifier.py#L377 保持一致

> bert_frozen_seq32.pb是从bert提供的BERT-Base, Chinese转过来的吗

不是

> 能否提供.ckpt转化为.pb的代码

可以搜一下 tensorflow freeze_graph 的用法

**Comment by everwind** [comment]
bert_frozen_seq32.pb 是如何得到的， @levyfan 是随机初始化的吗？

**Comment by levyfan** [comment]
不是，是我们内部较早使用过的一个模型
