### ISSUE TITLE
What mkl options have you used on benchmark?

### ISSUE THREAD

**Issue by hsh2438** [zhihu/cuBERT#34]
I am following your project now.
You marked 2x faster when you mkl, but there is no information about what options have you used.
Would you please let me know mkl option for benchmark performance.

**Comment by levyfan** [comment]
On our machine, best performance is achieved without any options. On README page, the benchmark is tested against `KMP_BLOCKTIME=0 KMP_AFFINITY=granularity=fine,verbose,compact,1,0`, which is the same with tensorflow (these options are suggested by tensorflow guide).
