### ISSUE TITLE
What's the setting of the benchmark?

### ISSUE THREAD

**Issue by leerumor** [zhihu/cuBERT#43]
On my CPU, I use CUBERT_NUM_CPU_MODELS=1, OMP_NUM_THREADS =8, MKL_NUM_THREADS =8, but got 37ms of run time.

P.S. the MKL-DNN library supports cpu int8, maybe you can improve the performance a little more

**Comment by levyfan** [comment]
CUBERT_NUM_CPU_MODELS does not affect runtime if you do not change OMP_NUM_THREADS.

OMP_NUM_THREADS: how many threads (or cpu cores) will 1 BERT model occupy.
CUBERT_NUM_CPU_MODELS: how many models in total.

**Comment by leerumor** [comment]
> CUBERT_NUM_CPU_MODELS does not affect runtime if you do not change OMP_NUM_THREADS.
> 
> OMP_NUM_THREADS: how many threads (or cpu cores) will 1 BERT model occupy.
> CUBERT_NUM_CPU_MODELS: how many models in total.

thanks!
so what's your setting for mklBERT/24ms?

**Comment by levyfan** [comment]
KMP_BLOCKTIME=0
KMP_AFFINITY=granularity=fine,verbose,compact,1,0

**Comment by leerumor** [comment]
> KMP_BLOCKTIME=0
> KMP_AFFINITY=granularity=fine,verbose,compact,1,0

thanks, finally i got 24ms using 17 cores ;)
