### ISSUE TITLE
mklBERT设置batch比较大的时候，性能很差，跟你的测试结果不一致。

### ISSUE THREAD

**Issue by comeby** [zhihu/cuBERT#48]
我的测试环境如下：
28 * Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
Ubuntu 16.04.5 LTS
gcc (Ubuntu5.4.0~6ubuntu1~16.04.11) 5.4.0 21060609
MKL: 2019.0.1.20181227
和你的环境只是系统和gcc版本不同。但我测试的mklBERT在batch=128的时候，不设置任何环境变量，解码时间要5000ms+，设置OMP_NUM_THREADS=28后解码时间需要2000ms+，batch=1时的解码时间和你的一致。请问可能是什么原因？

另外，我分别设置了OMP_NUM_THREADS、KMP_BLOCKTIME、KMP_AFFINITY这些参数。都没有达到README中给出的984.9ms的性能。

我是采用的cuBERT_benchmark进行测试的。我测试时，cuBERT_benchmark的解码时间波动很大，你们是怎么精确到小数位时间的？烦请指教，谢谢~

**Comment by levyfan** [comment]
解码时间波动很大，是否在测试过程中有其他程序在运行？确保测试时 cpu 没有什么进程占用吧。我们测试的波动不大。

**Comment by comeby** [comment]
你好。确定没有其他程序运行。比如batch=1时的解码时间：
=== warm_up ===
cuBERT: 412ms
cuBERT: 412ms
cuBERT: 412ms
cuBERT: 412ms
cuBERT: 412ms

**Comment by levyfan** [comment]
大部分时间都在 mkl 矩阵计算，可以尝试升级 mkl 版本，或者自己记录各个操作的执行时间

https://github.com/zhihu/cuBERT/blob/master/cmake/mkl.cmake

**Comment by AllenChennn** [comment]
>

> 你好。确定没有其他程序运行。比如batch=1时的解码时间：
> === warm_up ===
> cuBERT: 412ms
> cuBERT: 26ms
> cuBERT: 44ms
> cuBERT: 38ms
> cuBERT: 35ms
> ...
> ==== benchmark ===
> cuBERT: 29ms
> cuBERT: 30ms
> cuBERT: 24ms
> cuBERT: 24ms
> cuBERT: 25ms
> cuBERT: 24ms
> cuBERT: 24ms
> cuBERT: 30ms
> cuBERT: 79ms
> cuBERT: 100ms
> 这样子。
> 最主要问题在于，batch=128的时候解码时间比较大。波动倒不厉害。

hello，想问下你warmup的数据时怎么测试出来的
