### ISSUE TITLE
弱问怎么得到自己的bert_frozen_seq32.pb？

### ISSUE THREAD

**Issue by guotong1988** [zhihu/cuBERT#50]
怎么自己导出自己的pb文件然后能在这个项目load啊，
多谢！！
README里好像只有这个
![image](https://user-images.githubusercontent.com/4702353/65314231-7edf0d00-dbc8-11e9-8b26-5fc4b08e2b5a.png)

**Comment by levyfan** [comment]
搜一下 tensorflow freeze_graph 吧

https://leimao.github.io/blog/Save-Load-Inference-From-TF-Frozen-Graph/

**Comment by guotong1988** [comment]
还以为这里会提供哈~

**Comment by guotong1988** [comment]
自己freeze的怕多一层少一层不能用

**Comment by EasonChow001** [comment]
@levyfan 你好  能百度云盘共享下现成的pb文件吗？dropbox访问不了。单纯想快速验证下与onnxruntime之间的推理性能差异。
