### ISSUE TITLE
undefined reference to `cublasGemmStridedBatchedEx'

### ISSUE THREAD

**Issue by onlyone509** [zhihu/cuBERT#51]
cublasGemmStridedBatchedEx这个接口好像是cuda9.1才引入的，文档中介绍的依赖是9.0.176，链接的时候报错，请问是什么原因？

**Comment by levyfan** [comment]
cuda 9.0 后续有4个 patch，把这些 patch 安装了应该就可以

cuda_9.0.176.1_linux-run
cuda_9.0.176.2_linux-run
cuda_9.0.176.3_linux.run
cuda_9.0.176.4_linux.run

**Comment by onlyone509** [comment]
打完patch好像还是不行呢，错误还是一样的。

**Comment by onlyone509** [comment]
解决了，打完patch是可以的，是我这边安装的问题，多谢解答。
