### ISSUE TITLE
out of memory when seq_length=384 and batch_size=1

### ISSUE THREAD

**Issue by onlyone509** [zhihu/cuBERT#52]
environment:
tesla P40
把cuBERT_benchmark.py的batch_size改成1，seq_length改成384，直接运行，报out of memory错误。请问是什么原因？

**Comment by levyfan** [comment]
max_batch_size 也需要调整。显存申请是按照 max_batch_size 来的。

**Comment by onlyone509** [comment]
后来发现了，忘了来回复了。多谢。
