### ISSUE TITLE
build from source的时候遇到点问题

### ISSUE THREAD

**Issue by DamonCC** [zhihu/cuBERT#53]
在执行make -j4那里执行命令如下
`- git clone https://github.com/zhihu/cuBERT.git
      - cd cuBERT
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DcuBERT_ENABLE_GPU=ON -DCUDA_ARCH_NAME=Common ..
      - make -j4
      - make install`
然后报出了一点问题，查了一下不是很明白
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "9.0") 
-- Using CUDA arch flags: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61 sm_70 compute_70
-- Could NOT find tensorflow (missing: tensorflow_LIBRARIES tensorflow_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /cuBERT/build
Scanning dependencies of target googletest
Scanning dependencies of target cub
Scanning dependencies of target protobuf
[  1%] Creating directories for 'protobuf'
[  2%] Creating directories for 'googletest'
[  3%] Creating directories for 'cub'
[  5%] Performing download step (git clone) for 'protobuf'
[  5%] Performing download step (git clone) for 'googletest'
[  6%] Performing download step (download, verify and extract) for 'cub'
-- Downloading...
   dst='/cuBERT/build/cub/src/1.8.0.zip'
   timeout='none'
-- Using src='https://github.com/NVlabs/cub/archive/1.8.0.zip'
-- Retrying...
-- Using src='https://github.com/NVlabs/cub/archive/1.8.0.zip'
-- Retry after 5 seconds (attempt #2) ...
[  7%] No patch step for 'googletest'
[  8%] Performing update step for 'googletest'
[  9%] Performing configure step for 'googletest'
loading initial cache file /cuBERT/build/googletest/tmp/googletest-cache-Release.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/local/bin/python (found version "3.6.9") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /cuBERT/build/googletest/src/googletest
[ 10%] Performing build step for 'googletest'
Scanning dependencies of target gtest
[ 25%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
-- Using src='https://github.com/NVlabs/cub/archive/1.8.0.zip'
-- Retry after 5 seconds (attempt #3) ...
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/benchmark'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
-- Using src='https://github.com/NVlabs/cub/archive/1.8.0.zip'
-- Retry after 15 seconds (attempt #4) ...
Submodule path 'third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
Submodule path 'third_party/googletest': checked out 'c3bb0ee2a63279a803aaad956b9b26d74bf9e6e2'
[ 11%] No patch step for 'protobuf'
[ 12%] Performing update step for 'protobuf'
[ 13%] Performing configure step for 'protobuf'
[ 50%] Linking CXX static library libgtest.a
[ 50%] Built target gtest
Scanning dependencies of target gtest_main
[ 75%] Building CXX object googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[100%] Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
[ 14%] No install step for 'googletest'
[ 15%] Completed 'googletest'
[ 15%] Built target googletest
CMakeFiles/protobuf.dir/build.make:106: recipe for target 'protobuf/src/protobuf-stamp/protobuf-configure' failed
CMakeFiles/Makefile2:262: recipe for target 'CMakeFiles/protobuf.dir/all' failed
-- Using src='https://github.com/NVlabs/cub/archive/1.8.0.zip'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/NVlabs/cub/archive/1.8.0.zip'
CMakeFiles/cub.dir/build.make:90: recipe for target 'cub/src/cub-stamp/cub-download' failed
CMakeFiles/Makefile2:299: recipe for target 'CMakeFiles/cub.dir/all' failed
Makefile:140: recipe for target 'all' failed

**Comment by DamonCC** [comment]
Cloning into 'cuBERT'...
Cloning into 'protobuf'...
Cloning into 'googletest'...
Note: checking out 'ec44c6c1675c25b9827aacd08c02433cccde7780'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ec44c6c... Merge pull request #821 from mazong1123/master
Note: checking out 'v3.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ab8edf1... Merge pull request #4713 from acozzette/changelog
Cloning into 'third_party/benchmark'...
Cloning into 'third_party/googletest'...
+ autoreconf -f -i -Wall,no-obsolete
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
make[2]: *** [protobuf/src/protobuf-stamp/protobuf-configure] Error 1
make[1]: *** [CMakeFiles/protobuf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at cub-stamp/download-cub.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/NVlabs/cub/archive/1.8.0.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/NVlabs/cub/archive/1.8.0.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/NVlabs/cub/archive/1.8.0.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/NVlabs/cub/archive/1.8.0.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/NVlabs/cub/archive/1.8.0.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/NVlabs/cub/archive/1.8.0.zip' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         
    


make[2]: *** [cub/src/cub-stamp/cub-download] Error 1
make[1]: *** [CMakeFiles/cub.dir/all] Error 2
make: *** [all] Error 2

**Comment by DamonCC** [comment]
能帮我看一下吗？谢谢

**Comment by levyfan** [comment]
cmake 的问题，你如果是自己编译的 cmake，需要 `./bootstrap --system-curl`

**Comment by levyfan** [comment]
https://stackoverflow.com/questions/44633043/cmake-libcurl-was-built-with-ssl-disabled-https-not-supported

**Comment by levyfan** [comment]
https://leimao.github.io/blog/CMake-SSL-Support/

**Comment by DamonCC** [comment]
cmake的问题我已经解决了，后面make -j4的时候又报了这个错，我看了closed里面的issue，发现有个类似的是gcc版本过低，我的gcc是5.4.0，应该是满足要求的
[ 47%] Linking C static library libtf_protos_cc.a
[ 57%] Built target tf_protos_cc
Scanning dependencies of target cuBERT
[ 58%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/common.cpp.o
[ 58%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/BertM.cpp.o
[ 59%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/GELU.cpp.o
[ 60%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/tensorflow/Graph.cpp
.o
/cuBERT/src/cuBERT/common.cpp:15:2: error: #error only one and extact one blas i
mplementation should be selected
 #error only one and extact one blas implementation should be selected
  ^
[ 61%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/Dense.cpp.o
[ 62%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/Embedding.cpp.o
CMakeFiles/cuBERT.dir/build.make:3700: recipe for target 'CMakeFiles/cuBERT.dir/
src/cuBERT/common.cpp.o' failed
make[2]: *** [CMakeFiles/cuBERT.dir/src/cuBERT/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:147: recipe for target 'CMakeFiles/cuBERT.dir/all' failed
make[1]: *** [CMakeFiles/cuBERT.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DamonCC** [comment]
你好，能再给看看吗？build cuda的问题不知道咋解决
Scanning dependencies of target cuBERT
[ 59%] Building C object CMakeFiles/cuBERT.dir/src/utf8proc/utf8proc.c.o
[ 59%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT.cpp.o
[ 60%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/common.cpp.o
[ 61%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/tokenization.cpp.o
[ 62%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/Bert.cpp.o
[ 63%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/BertM.cpp.o
[ 64%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/tensorflow/Graph.cpp.o
[ 65%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/GELU.cpp.o
[ 66%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/Dense.cpp.o
[ 67%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/Embedding.cpp.o
[ 68%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/Softmax.cpp.o
[ 69%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op/LayerNorm.cpp.o
[ 70%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op_att/AttentionSelf.cpp.o
[ 71%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op_att/AttentionMask.cpp.o
[ 72%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op_att/BatchMatMul.cpp.o
[ 73%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op_att/Transformer.cpp.o
[ 74%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op_bert/BertEmbeddings.cpp.o
[ 75%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op_bert/BertPooler.cpp.o
[ 76%] Building CXX object CMakeFiles/cuBERT.dir/src/cuBERT/op_out/AdditionalOutputLayer.cpp.o
[ 77%] Linking CXX shared library libcuBERT.so
[ 77%] Built target cuBERT
Scanning dependencies of target cuBERT_benchmark
Scanning dependencies of target gemm_benchmark
[ 78%] Building CXX object CMakeFiles/cuBERT_benchmark.dir/benchmark/benchmark_cu.cpp.o
[ 79%] Building CXX object CMakeFiles/gemm_benchmark.dir/benchmark/benchmark_gemm.cpp.o
Scanning dependencies of target cuBERT_test
[ 80%] Building CXX object CMakeFiles/cuBERT_test.dir/test/unit_test.cpp.o
[ 81%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/common_test.cpp.o
[ 82%] Linking CXX executable gemm_benchmark
CMakeFiles/gemm_benchmark.dir/build.make:101: recipe for target 'gemm_benchmark' failed
CMakeFiles/Makefile2:332: recipe for target 'CMakeFiles/gemm_benchmark.dir/all' failed
[ 83%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/tokenization_test.cpp.o
[ 84%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op/DenseTest.cpp.o
[ 85%] Linking CXX executable cuBERT_benchmark
CMakeFiles/cuBERT_benchmark.dir/build.make:101: recipe for target 'cuBERT_benchmark' failed
CMakeFiles/Makefile2:183: recipe for target 'CMakeFiles/cuBERT_benchmark.dir/all' failed
[ 86%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op/LayerNormTest.cpp.o
[ 87%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op/SoftmaxTest.cpp.o
[ 88%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op/GELUTest.cpp.o
[ 89%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op/EmbeddingTest.cpp.o
[ 90%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op_att/BatchMatMulTest.cpp.o
[ 91%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op_att/AttentionSelfTest.cpp.o
[ 92%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op_att/TransformerTest.cpp.o
[ 93%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op_att/AttentionMaskTest.cpp.o
[ 94%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op_bert/BertEmbeddingsTest.cpp.o
[ 95%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op_bert/BertPoolerTest.cpp.o
[ 96%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/op_out/AdditionalOutputLayerTest.cpp.o
[ 97%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/BertTest.cpp.o
[ 98%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT/BertMTest.cpp.o
[ 99%] Building CXX object CMakeFiles/cuBERT_test.dir/test/cuBERT_test.cpp.o
[100%] Linking CXX executable cuBERT_test
CMakeFiles/cuBERT_test.dir/build.make:544: recipe for target 'cuBERT_test' failed
CMakeFiles/Makefile2:370: recipe for target 'CMakeFiles/cuBERT_test.dir/all' failed
Makefile:140: recipe for target 'all' failed






If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1390409... Merge pull request #384 from protobuf-c/edmonds/version/1.3.2
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:14: installing 'build-aux/compile'
configure.ac:22: installing 'build-aux/config.guess'
configure.ac:22: installing 'build-aux/config.sub'
configure.ac:13: installing 'build-aux/install-sh'
configure.ac:13: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: Leaving directory `.'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: t/test.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: t/test-full.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: t/test-optimized.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: t/test-full.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: t/issue220/issue220.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: t/issue251/issue251.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
ar: `u' modifier ignored since `D' is the default (see `U')
libcuBERT.so: undefined reference to `cublasGemmBatchedEx'
libcuBERT.so: undefined reference to `cublasGemmStridedBatchedEx'
collect2: error: ld returned 1 exit status
make[2]: *** [gemm_benchmark] Error 1
make[1]: *** [CMakeFiles/gemm_benchmark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libcuBERT.so: undefined reference to `cublasGemmBatchedEx'
libcuBERT.so: undefined reference to `cublasGemmStridedBatchedEx'
collect2: error: ld returned 1 exit status
make[2]: *** [cuBERT_benchmark] Error 1
make[1]: *** [CMakeFiles/cuBERT_benchmark.dir/all] Error 2
libcuBERT.so: undefined reference to `cublasGemmBatchedEx'
libcuBERT.so: undefined reference to `cublasGemmStridedBatchedEx'
collect2: error: ld returned 1 exit status
make[2]: *** [cuBERT_test] Error 1
make[1]: *** [CMakeFiles/cuBERT_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by DamonCC** [comment]
或者有build成功的docker能分享一下吗？

**Comment by levyfan** [comment]
cuda 版本问题，你如果是 cuda 9.0 必须要安装后续的 patch：
Patch 1 (Released Jan 25, 2018)
Patch 2 (Released Mar 5, 2018)
Patch 3 (Released Jun 7, 2018)
Patch 4 (Released Aug 6, 2018)

**Comment by levyfan** [comment]
docker: https://hub.docker.com/r/levyfan/cubert/tags

**Comment by DamonCC** [comment]
好的，收到，感谢
