### ISSUE TITLE
在进行build时执行cmake -DCMAKE_BUILD_TYPE=Release -DcuBERT_ENABLE_MKL_SUPPORT=ON ..  make -j4，报错

### ISSUE THREAD

**Issue by manutd12** [zhihu/cuBERT#77]
在进行build时，执行
cmake -DCMAKE_BUILD_TYPE=Release -DcuBERT_ENABLE_MKL_SUPPORT=ON ..  
make -j4
在执行 make -j4时，报了如下图中的错误。请问如何解决呢？
![image](https://user-images.githubusercontent.com/48948802/103873178-6458dc00-510a-11eb-8928-0605b0a64170.png)

报错信息：
[ 34%] Performing update step for 'protobuf'
[ 34%] No patch step for 'protobuf'
[ 35%] Performing configure step for 'protobuf'
+ autoreconf -f -i -Wall,no-obsolete
aclocal: couldn't open directory `m4': 没有那个文件或目录
autoreconf: aclocal failed with exit status: 1
make[2]: *** [protobuf/src/protobuf-stamp/protobuf-configure] 错误 1
make[1]: *** [CMakeFiles/protobuf.dir/all] 错误 2

**Comment by levyfan** [comment]
需要安装 autotools (autoconf, automake, libtool)

**Comment by manutd12** [comment]
> 需要安装 autotools (autoconf, automake, libtool)

您好，安装 autotools后此问题解决了。但是在build过程中又遇到一个新的问题。
如下所示，在进行到Built target tf_protos_cc这一步时，download速度特别慢，12个小时只下载了6%。请问这一步是在下载什么内容，有什么方式可以加快下载速度呢？谢谢！

[ 40%] Completed 'protobuf-c'
[ 40%] Built target protobuf-c
[ 41%] Running C protocol buffer compiler on tensorflow/core/framework/versions.proto
[ 42%] Running C protocol buffer compiler on tensorflow/core/framework/attr_value.proto
[ 43%] Running C protocol buffer compiler on tensorflow/core/framework/graph.proto
[ 44%] Running C protocol buffer compiler on tensorflow/core/framework/node_def.proto
[ 46%] Running C protocol buffer compiler on tensorflow/core/framework/resource_handle.proto
[ 46%] Running C protocol buffer compiler on tensorflow/core/framework/function.proto
[ 46%] Running C protocol buffer compiler on tensorflow/core/framework/op_def.proto
[ 47%] Running C protocol buffer compiler on tensorflow/core/framework/tensor.proto
[ 48%] Running C protocol buffer compiler on tensorflow/core/framework/types.proto
[ 49%] Running C protocol buffer compiler on tensorflow/core/framework/tensor_shape.proto
Scanning dependencies of target tf_protos_cc
[ 50%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/attr_value.pb-c.c.o
[ 51%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/node_def.pb-c.c.o
[ 52%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/op_def.pb-c.c.o
[ 54%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/graph.pb-c.c.o
[ 54%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/function.pb-c.c.o
[ 55%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/tensor.pb-c.c.o
[ 55%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/resource_handle.pb-c.c.o
[ 58%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/tensor_shape.pb-c.c.o
[ 58%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/types.pb-c.c.o
[ 58%] Building C object CMakeFiles/tf_protos_cc.dir/tensorflow/core/framework/versions.pb-c.c.o
[ 59%] Linking C static library libtf_protos_cc.a
[ 59%] Built target tf_protos_cc
-- [download 5% complete]
-- [download 6% complete]

**Comment by levyfan** [comment]
下载 protobuf，自己用 vpn 吧
