### ISSUE TITLE
在cpu上的cubert推理速度比tf_bert慢

### ISSUE THREAD

**Issue by manutd12** [zhihu/cuBERT#78]
您好，我在cpu 48线程上测试，cubert推理速度要比tf_bert慢。 我的mkl版本是2018版本，请问mkl版本对于cubert推理速度是否会造成影响？
我的cpu是 48  Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz

**Comment by levyfan** [comment]
有直接影响，可以尝试最新版本
