### ISSUE TITLE
关于test中模型的其他输出

### ISSUE THREAD

**Issue by zlwzlwzlw** [zhihu/cuBERT#79]
在GPU环境下我想把例子cuBERT_test.cpp中的cuBERT_LOGITS输出替换替换成cuBERT_SEQUENCE_OUTPUT
cuBERT_tokenize_compute(model, tokenizer, batch_size,
                            text_a,
                            text_b,
                            output, cuBERT_SEQUENCE_OUTPUT);
一直报段错误，这个怎么解决？

**Comment by levyfan** [comment]
需要为 output 开辟更大的内存空间
